lr: 0.0004
seed: 3
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 256
val_batch: 256
test_batch: 256
num_workers: 8
model_name: 'refine-64'
data_filepath: './data/'
dataset: 'double_pendulum'
lr_schedule: [15, 30, 100, 300]
num_gpus: 1
epochs: 1000